engines:
  checkstyle:
    enabled: true
  duplicateion:
    enabled: true
    config:
      languages:
      - java
  pmd:
    enabled: true
ratings:
  paths:
  - "**.java"
exclude_paths:
- web/src/main/webapp/*